# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rogue
markdown: kramdown
disqus: Shengting Cao
google_analytics: Shengting Cao
title: Shengting Cao

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: shengting cao

description: Stylish Jekyll Theme
disqus: dbyll-ghost # add disqus short name here
author:
  name: scao7
  email: codescao7@gmail.com
  github: scao7
  twitter: scao7
  pinterest: scao7
  linkedin: scao7
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 
# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

gems:
  - jekyll-paginate
